# Generated by Django 5.1 on 2024-08-29 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_todo_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
